.EF.
======================================================================
ERROR: test_dummy_exception (testrunner.tests.test_forms.FormsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulcooper/Documents/GitHub/pbchallenge/testrunner/tests/test_forms.py", line 19, in test_dummy_exception
    raise TypeError
TypeError

======================================================================
FAIL: test_dummy_fail (testrunner.tests.test_forms.FormsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paulcooper/Documents/GitHub/pbchallenge/testrunner/tests/test_forms.py", line 16, in test_dummy_fail
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 20.003s

FAILED (failures=1, errors=1)
